=== Hl4p3x/L2jOrion_Interlude_C6/L2jOrion_Datapack/game/data/xml/xsd/CursedWeapons.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dropRate">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:int" name="val" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="duration">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:int" name="val" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="durationLost">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:int" name="val" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="disapearChance">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:int" name="val" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="stageKills">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:int" name="val" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:int" name="id" use="required"/>
						<xs:attribute type="xs:int" name="skillId" use="required"/>
						<xs:attribute type="xs:string" name="name" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hl4p3x/L2jOrion_Interlude_C6/L2jOrion_Datapack/game/data/xml/cursedWeapons.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/CursedWeapons.xsd">
	<item id="8190" skillId="3603" name="Demonic Sword Zariche">
		<dropRate val="1" /> <!-- 1000000 for 100% -->		
		<duration val="4320" /> <!-- in minutes -->		
		<durationLost val="1440" /> <!-- in minutes -->		
		<disapearChance val="50" /> <!-- in % -->		
		<stageKills val="10" /> <!-- Integer -->		
	</item>
	<item id="8689" skillId="3629" name="Blood Sword Akamanah">
		<dropRate val="1" /> <!-- 1000000 for 100% -->		
		<duration val="4320" /> <!-- in minutes -->		
		<durationLost val="1440" /> <!-- in minutes -->		
		<disapearChance val="50" /> <!-- in % -->		
		<stageKills val="10" /> <!-- Integer -->		
	</item>
</list>
